- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create an IPv4 firewall rule
    nttmcp.mcp.firewall:
      region: "{{region}}"
      datacenter: "{{datacenter}}"
      network_domain: "{{cnd}}"
      name: monitoring_rule_all
      protocol: TCP
      src_cidr: "90.254.31.4"
      src_port_start: ANY
      dst_cidr: "168.128.106.48/32"
      dst_port_start: ANY
      dst_port_end: ANY